package conf

type AutoGenerated struct {
	Server Server `yaml:"server"`
	Mysql  Mysql  `yaml:"mysql"`
	App    App    `json:"app"`
}

type Server struct {
	Port    int64  `yaml:"port"`
	JwtSign string `yaml:"jwtSign"`
}

type Mysql struct {
	Host     string `yaml:"host"`
	Port     int64  `yaml:"port"`
	Username string `yaml:"username"`
	Password string `yaml:"password"`
}

type App struct {
	Notice string `json:"notice"`
}
